### ISSUE TITLE
New version!

### ISSUE THREAD

**Issue by BoomBookTR** [Drawbackz/DevCon-Installer#5]
I found new version... i installed from not iso...Online setup way. i found links from Setup Logs...

Here is Windows 11 Insider Preview WDK 22000.1.210604-1628 ISO...
http://software-download.microsoft.com/download/sg/22000.1.210604-1628.co_release_amd64fre_WDK.iso

Official Links 

82c1721cd310c73968861674ffc209c9.cab >> includes fil5a9177f816435063f779ebbbd2c1a1d2 <<<<\x86\devcon.exe
Cab Link: https://download.microsoft.com/download/7/d/6/7d602355-8ae9-414c-ae36-109ece2aade6/wdk/Installers/82c1721cd310c73968861674ffc209c9.cab

787bee96dbd26371076b37b13c405890.cab >> includes filbad6e2cce5ebc45a401e19c613d0a28f <<<<\x64\devcon.exe
Cab Link: https://download.microsoft.com/download/7/d/6/7d602355-8ae9-414c-ae36-109ece2aade6/wdk/Installers/787bee96dbd26371076b37b13c405890.cab

efbfda9cedfdb8edf40e90ff75bdf53f.cab >> includes filbb70b72d1e982e63540543878868d859 <<<<\arm\devcon.exe
Cab Link: https://download.microsoft.com/download/7/d/6/7d602355-8ae9-414c-ae36-109ece2aade6/wdk/Installers/efbfda9cedfdb8edf40e90ff75bdf53f.cab

f894d1292c50e75ebb4ba8e6eb2fe237.cab >> includes fil04c5204d326cce9cf9440d47603364df <<<<\arm64\devcon.exe
Cab Link: https://download.microsoft.com/download/7/d/6/7d602355-8ae9-414c-ae36-109ece2aade6/wdk/Installers/f894d1292c50e75ebb4ba8e6eb2fe237.cab

**Comment by Drawbackz** [comment]
Thanks! I will get these added.
